# Generated by Django 4.1.4 on 2023-01-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminhod',
            name='id',
            field=models.UUIDField(default='52e23d0edb4b449f820645f17d30afd2', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.UUIDField(default='52e23d0edb4b449f820645f17d30afd2', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='id',
            field=models.UUIDField(default='52e23d0edb4b449f820645f17d30afd2', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courses',
            name='id',
            field=models.UUIDField(default='52e23d0edb4b449f820645f17d30afd2', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedbackstaffs',
            name='id',
            field=models.UUIDField(default='52e23d0edb4b449f820645f17d30afd2', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedbackstudent',
            name='id',
            field=models.UUIDField(default='52e23d0edb4b449f820645f17d30afd2', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leavereportstaff',
            name='id',
            field=models.UUIDField(default='52e23d0edb4b449f820645f17d30afd2', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='id',
            field=models.UUIDField(default='52e23d0edb4b449f820645f17d30afd2', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notificationstaffs',
            name='id',
            field=models.UUIDField(default='52e23d0edb4b449f820645f17d30afd2', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notificationstudent',
            name='id',
            field=models.UUIDField(default='52e23d0edb4b449f820645f17d30afd2', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='id',
            field=models.UUIDField(default='52e23d0edb4b449f820645f17d30afd2', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.UUIDField(default='52e23d0edb4b449f820645f17d30afd2', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='id',
            field=models.UUIDField(default='52e23d0edb4b449f820645f17d30afd2', editable=False, primary_key=True, serialize=False),
        ),
    ]
