# Generated by Django 4.1.4 on 2023-01-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0003_remove_user_admin_alter_adminhod_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
