# Generated by Django 4.1.4 on 2023-01-29 06:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0005_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_start_year', models.IntegerField()),
                ('session_end_year', models.IntegerField()),
                ('courses', models.ManyToManyField(related_name='courses', to='school_management.subject')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.department')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
