# Generated by Django 4.1.4 on 2023-01-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0006_courseregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='class_grade',
            field=models.CharField(choices=[('freshman', 'freshaman'), ('sophomore', 'sophomore'), ('junior', 'junior'), ('senior', 'senior')], default='junior', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(3, 'HOD'), (2, 'staff'), (1, 'student')]),
        ),
    ]
