# Generated by Django 4.1.4 on 2023-01-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0009_alter_subject_class_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='course_code',
            field=models.CharField(default='HIS101', max_length=255),
            preserve_default=False,
        ),
    ]
