# Generated by Django 4.1.4 on 2023-01-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0010_subject_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='course_type',
            field=models.CharField(choices=[('core', 'core'), ('elective', 'elective')], default='core', max_length=255),
        ),
    ]
