# Generated by Django 4.1.4 on 2023-01-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0011_subject_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='+2349014642748', max_length=255),
        ),
    ]
