# Generated by Django 4.1.4 on 2023-01-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0013_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='joshua@creditchek.africa', max_length=255),
        ),
    ]
