# Generated by Django 4.1.4 on 2023-02-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0016_user_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isTuitionPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='campus',
            field=models.CharField(max_length=255),
        ),
    ]
